### ISSUE TITLE
Excited to give it a test!

### ISSUE THREAD

**Issue by awesomebytes** [jsford64/jiffy-compression#1]
Hey, just read your publication "Lossless SIMD Compression of LiDAR Range and Attribute Scan Sequences". Great work!

I saw in the paper a link to this repository. I am excited to give a try to your compression algorithm. I have access to a few different LIDAR sensors, so I would be keen to see how well it performs in them.

Also, Merry Xmas if you celebrate the period :)

**Comment by jsford64** [comment]
Hi Sam,

Sorry for the very late reply, holidays and other things got in the way.

I intended to clean up the research code before I made it publicly available, but since you would like to try it, I can give you private access if you like.

The code is overly complex right now, mainly because I built it to be easily modified to try various combinations of compression methods, it has a slightly clunky API, and I was trying out some new-to-me Python features at the same time (primarily dataclasses). 

The research code does not read the lidar source files directly, we decided to store them in a proprietary numpy-based format instead, and they are unfortunately too large to fit on GitHub for you to download.

Despite that, if you can format the lidar scan data into a numpy array format, it should be pretty easy for you to try it out.

Let me know if you are still interested.

Jeff

**Comment by awesomebytes** [comment]
Hello @jsford64 I would be interested, indeed.
I can transform any of our existing pointclouds/LIDAR scans into your input format (I use ROS, so the data usually comes from some ROS driver). I may take some time to be able to do anything as I'm a bit swamped with stuff right now, though! (Kinda depends on how much work do I need to do in order to quickly test your system).

**Comment by jsford64** [comment]
Let me put a simple example together and I will send you an invitation.

Jeff

**Comment by jsford64** [comment]
Sorry for the extremely late code posting. I went through a significant rewrite of the code and added a Jiffy file format.

Let me know if you have any issues or questions.

Jeff
